// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF0mI2gEhbYwFgl8LBuMQe0bhRManycTw',
    appId: '1:162603654833:web:9bab0e698d69f80d364c90',
    messagingSenderId: '162603654833',
    projectId: 'flutter-chat-app-d44e0',
    authDomain: 'flutter-chat-app-d44e0.firebaseapp.com',
    storageBucket: 'flutter-chat-app-d44e0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxgCcGnWnwq18Rt7Rmsud19Rgks3XneaI',
    appId: '1:162603654833:android:cc28aea595d49a59364c90',
    messagingSenderId: '162603654833',
    projectId: 'flutter-chat-app-d44e0',
    storageBucket: 'flutter-chat-app-d44e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTaxV3ApGkcrou7U65dHufAkSRvBgEiqo',
    appId: '1:162603654833:ios:4d237c95762df987364c90',
    messagingSenderId: '162603654833',
    projectId: 'flutter-chat-app-d44e0',
    storageBucket: 'flutter-chat-app-d44e0.appspot.com',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTaxV3ApGkcrou7U65dHufAkSRvBgEiqo',
    appId: '1:162603654833:ios:cae179dc3748b2fe364c90',
    messagingSenderId: '162603654833',
    projectId: 'flutter-chat-app-d44e0',
    storageBucket: 'flutter-chat-app-d44e0.appspot.com',
    iosBundleId: 'com.example.firstApp.RunnerTests',
  );
}
